### ISSUE TITLE
Explore scenarios to use azure-pipelines for CI/CD

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-server-connector#142]
Currently we are using travis for the ci/cd pipeline. But it does not support Windows. 

As MSFT has released azure-pipelines for support on wind/macOS/linux, it can be a viable option as it is free for open source projects.

**Comment by jeffmaury** [comment]
I'm using AppVeyor for Windows validation in fabric8-launcher-vscode-extension

**Comment by adietish** [comment]
@mohitsuman @jeffmaury dare to please specify what you expect in this issue? Is this resolved? If yes, dare to share you knowledge ideally here, please?

**Comment by mohitsuman** [comment]
@adietish The idea behind using Azure pipelines is to maintain and improve our build and continuous integration (CI) infrastructure. Currently we use `Jenkins`(Win specific)or `AppVeyor` (as Jeff mentioned) and `Travis` (macOS and linux) to cater to the CI build.

Now by adopting to Azure pipelines, our builds now run simultaneously across all 3 platforms like in the case for `openshift-connector` (https://dev.azure.com/redhat-developer/vscode-openshift-tools/_build?definitionId=1).

I will configure the same for this extension too, so that we have consistency across the CI environment for our adapter repos.
