### ISSUE TITLE
Provide command to restart rsp-server 

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-server-connector#176]
This would be used as escape door in case of emergency.

**Comment by adietish** [comment]
We now offer 3 ways to restart a server:
* Restart in debug mode #327
* Restart in run mode #55 
* Terminate if the server is stuck starting/stopping #349

Closing as DONE.

**Comment by robstryker** [comment]
I think denis meant the RSP itself... not a server managed by rsp like wildfly16 or similar.

**Comment by lstocchi** [comment]
Currently we also offer to terminate RSP if it is stuck to starting/stopping. Is it enough? It's a valid escape door in case of emergency

**Comment by robstryker** [comment]
Current UI can terminate an RSP, can start an RSP, and can stop an RSP.  It seems this usecase is covered.
