### ISSUE TITLE
create a screencast that shows publishing in vscode-adapters

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-server-connector#196]
this is a subtask to #192

**Comment by adietish** [comment]
assigning to @mohitsuman which offered to tackle this, thx!

**Comment by adietish** [comment]
moving to `devex #163`

**Comment by lstocchi** [comment]
Closing it as Rob created a video where he explains everything https://www.youtube.com/watch?v=sP2Hlw-C_7I
