### ISSUE TITLE
Should show output channel if error starting a sever occurs

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-server-connector#231]
this follows up on discussions in #224

@dgolovin:
> we might want to have another option popUpOnErrorOutput and it would make sense to have it set to true by default.

**Comment by adietish** [comment]
moving to `devex #163`

**Comment by lstocchi** [comment]
This can be closed. A patch for this kind of enhancement has already been merged long ago. The default setting for showing the output channel when new content is available is set to true.
