### ISSUE TITLE
consider extracting node_module for java checks

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-server-connector#232]
In vscode-adapter we reused code from vscode-java to check if there's java installed and if what version it is. We should thus consider extracting a node module and reuse it in vscode-adapters and vscode-java

**Comment by robstryker** [comment]
I'm a bit confused what you mean here. We're using vscode-java, which seems extracted already, no? Or are you suggesting stealing just those functions we require and creating a new node module with only the stuff we need? 

I guess I just don't grok the suggestion.

**Comment by dgolovin** [comment]
You did grok it, we should extract java check from java-vscode as a npm module. Then java-vscode and adapters can use the same module.

**Comment by robstryker** [comment]
Isn't it already an npm module?  I'm confused :(

**Comment by adietish** [comment]
@robstryker no it isn't a module yet. We copied the code over from vscode-java.

**Comment by robstryker** [comment]
I don't think this is necessary.
