### ISSUE TITLE
Improve/reduce number of prompts when downloading a runtime

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-server-connector#274]
tries to fix #271 

There are several prompt which the user simply has to confirm via "continue".  These are annoying and misleading since it's too easy to try to provide your username in the text field and then notice that it's not possible. You then have to remove your input and hit "continue".

steps:
1. EXEC: pick "Download Runtime" in context menu of the "Servers" view
2. ASSERT: list of available runtimes is presented in quick pick list
3. EXEC: choose JBoss EAP 7.0 (or any other EAP)

Result:
![image](https://user-images.githubusercontent.com/25126/54028267-ccec7000-41a4-11e9-9cde-09bde93efc60.png)
You get a quick pick where there's just an info being displayed which one has to confirm with "continue"

**Comment by adietish** [comment]
the PR for this is at #271

**Comment by lstocchi** [comment]
PR is now at https://github.com/redhat-developer/vscode-rsp-ui/pull/76

**Comment by robstryker** [comment]
PR was merged: https://github.com/redhat-developer/vscode-rsp-ui/pull/76
