### ISSUE TITLE
Server runtime keeps running even though rsp-server died

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-server-connector#314]
steps: 
1. ASSERT: have extension and ex. a wildfly server running
1. EXEC: kill server (felix)
1. EXEC: on the command line, check if wildfly is running.

Result:
Wildfly is still running even though rsp-server (felix) was killed.

This is related to #313 
This is related to #176

**Comment by lstocchi** [comment]
Hi @M-CatchOr, thanks for the feedback. Which version of server connector extension and remote server protocol UI extension are you using?

**Comment by M-CatchOr** [comment]
- `Server Connector`
  ```Name: Server Connector
  Id: redhat.vscode-server-connector
  Description: Allows to start, stop and deploy to Red Hat server and runtime products like Wildfly, JBoss EAP (Enterprise Application Platform), Minishift, CDK (Container Development Kit).
  Version: 0.21.1
  Publisher: Red Hat
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-server-connector```
- `Remote Server Protocol UI`
  ```Name: Remote Server Protocol UI
  Id: redhat.vscode-rsp-ui
  Description: Provides a unified UI to interact with runtimes and servers managed over the RSP protocol.
  Version: 0.21.0
  Publisher: Red Hat
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-rsp-ui```

**Comment by lstocchi** [comment]
I'm not able to replicate it. It's weird because in the deactivate method (which is called everytime vscode and the extension are closed) we check all servers and stop the started ones. It may happen if rsp-server fails to stop the server. @M-CatchOr do you have this issue everytime you close vscode or is it random?

**Comment by M-CatchOr** [comment]
I've checked again.  
It's not killed when I close `vscode` just after it appears.  
And also it's not killed when closed while on `wf` is on `debug`.

**Comment by robstryker** [comment]
When a server like wfly is running in debug mode, it appears the rsp and the wfly are not killed when closing eclipse. I was able to replicate this. 2x

**Comment by robstryker** [comment]
https://github.com/Microsoft/vscode/issues/47881

After reading this issue, there's some things to note here. First, all the extensions are run in "extension host process", a separate process. This process appears to manage all extensions. When the UI is shut down, this extension process has 5 seconds to shut down ALL extensions. 

It seems to me that some other extensions (like java debugger) are hogging this 5 seconds. I can't verify the full details here, whether this process shuts down all extensions in their own thread and so each thread has 5 seconds, or whether it's done consecutively and so our extension might only have 1 or 2 seconds remaining. It's unclear to me at this time. 

With that in mind, our extension currently will attempt to make a request to shut down all servers from all RSP Providers, and THEN shut down those servers. If the extension host process gets terminated early, our RSP might receive none of these requests, or might only receive requests to stop some server adapters, etc etc.  

A possible fix seems to be to iterate through all active RSPs and just tell them to shut themselves down, and their various runtimes. Once the RSP receives this request, it can shut down its server adapters on its own time, and then terminate itself cleanly. So the requests to stop specific server adapters is wasted. The RSP already does that. 

I'll test whether this fixes it or not, but, it will at least be an improvement. VSCode might eventually need to expand this shutdown time if there are a lot of extensions and this becomes a bigger problem for them. Until that time, though, we should do what we can to mitigate the issue.

**Comment by robstryker** [comment]
See https://github.com/redhat-developer/vscode-rsp-ui/pull/73

**Comment by robstryker** [comment]
@lstocchi  Can you verify this is still an issue?

**Comment by odockal** [comment]
What @adietish reported still happens. If one tries to kill felix manually, ie. wildfly server process keeps running. This counts for debugging as well.

Although, closing vscode itself will eventually terminate all processes connected to rsp and wildfly respectively, unless server is in debug mode, then you end up with rsp and wildfly process running after vscode is gone.

**Comment by robstryker** [comment]
> What @adietish reported still happens. If one tries to kill felix manually, ie. wildfly server process keeps running. This counts for debugging as well.

There's literally no defense against this. If you kill felix manually, kill your spawned wfly manually also ;) 

> Although, closing vscode itself will eventually terminate all processes connected to rsp and wildfly respectively, unless server is in debug mode, then you end up with rsp and wildfly process running after vscode is gone.

Nothing I can do here. I've optimized the shutdown as much as possible to run in separate threads and to make sure that the requests to each rsp to shutdown return as fast as possible.
