### ISSUE TITLE
Allow vscode-adapters to be built off snapshot of rsp-client

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/vscode-server-connector#351]
Not sure if the work here needs to be done in rsp-client or vscode-adapters, but, somehow we need to get vscode-adapters to build off of a snapshot of rsp-client.

**Comment by adietish** [comment]
This is blocked by https://github.com/redhat-developer/rsp-client/issues/91

**Comment by odockal** [comment]
@jrichter1 Can you please update on this issue as the issue was moved a bit? Thanks!

**Comment by jrichter1** [comment]
- rsp-client in now consumed by the UI extension instead, enabled building agains snapshots in https://github.com/redhat-developer/vscode-rsp-ui/commit/d06d9c9b05b9b7ea70d168bab772c2dbece56cec
 - also enabled builds with server-connector-api snapshots in https://github.com/redhat-developer/vscode-server-connector/commit/8542ae617483f6ec3afc5deb83c9e5f8fd17e8bf

I think this is done.

**Comment by odockal** [comment]
@jrichter1 Thanks for updates!
