### ISSUE TITLE
Deployment disappears upon restarting vscode

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-server-connector#362]
Steps:
1. ASSERT: have a server (ex. wildfly 16)
1. EXEC: add a deployment to it (ex. wildfly quickstarts/kitchensink, exploded war in target/kitchensink)
1. ASSERT: deployment is listed as child node to your server in "Servers" view
1. ASSERT: wait for it to get published (Autopublisher) 
1. EXEC: quit and restart vscode

Result:
Deployment is not listed any more, there's no child node to your server any more.
Nevertheless if one restarts the server (it was terminated when vscode was quit) and then looks at the server log, one can still see it being deployed to the server

**Comment by redking00** [comment]
Result:
For me, there is no server any more on treeview.
I can fixit removing deployment from server configuration on $home/.org.jboss.tools.rsp.data
Server is now on treeview but obviously deployment has gone.

I have the impression that what is wrong is related to deployment options. May be is a rsp-server bug?

**Comment by robstryker** [comment]
Can someone here contribute a server data file that is not being read properly? If you can share the contents of a wf17 data file that lives in ~/.org.jboss.tools.rsp.server/servers etc  then I can try to replicate?

**Comment by redking00** [comment]
You can replicate the issue by creating a named exploded deployment, it is not specific to wf17. I'll send you an example tomorrow.

**Comment by redking00** [comment]
Forgot to say my system is win10

**Comment by redking00** [comment]
Opened an issue and pull request on rsp-server

**Comment by lstocchi** [comment]
Can this be closed? @robstryker 
https://github.com/redhat-developer/rsp-server/issues/406

**Comment by robstryker** [comment]
I believe it's fixed. QE please verify.
