### ISSUE TITLE
Make Server Connector more prominent in marketplace

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-server-connector#363]
I started thinking about it when André showed us the extension called "Tomcat Adapter for VSCode". This extension has something like 80k+ installs but it doesn't do anything special. So why so many installs? Their strength is that they are easy to find. 
if you search for Tomcat in the marketplace, they are the only result.
![tomcat](https://user-images.githubusercontent.com/49404737/59332353-48a30f00-8cf6-11e9-9105-b6d3b365f218.png)

Now... what about Server Connector? Of course we cannot compete with them on Tomcat yet but our extension/page in the marketplace is not even optimized for our other target keywords. 
Wildfly? 0 results .... Eap? 0 results ... 
![wildfly](https://user-images.githubusercontent.com/49404737/59332581-de3e9e80-8cf6-11e9-9c23-45e9362b298f.png)

The description page is also very old and should be updated.

Is there someone in charge to do this kind of job (marketing dept.)? or we do take care of it? Maybe vscode marketplace has also some kind of keyword analyzer tool which can help us finding new keywords to target.

**Comment by adietish** [comment]
Fully agree here. If users can't find us easily (like with the evident 'wildfly' keyword) how would they know or even install our extension?

**Comment by adietish** [comment]
and as @lstocchi pointed out, there's a keyword section in package.json:
```
  "keywords": [
    "server",
    "runtimes",
    "middleware",
    "minishift",
    "adapters"
  ],
```
and these are used when you search in marketplace:
![image](https://user-images.githubusercontent.com/25126/59340671-b8b99100-8d06-11e9-96dc-302bd932b067.png)

So in my opinion, wildfly needs to be included in those, no doubt about it.

**Comment by robstryker** [comment]
Don't forget jboss and red hat =P 

+1 good find

**Comment by lstocchi** [comment]
The situation has been improved. Now this extension can be found for a bunch of keywords.

- "server",
- "runtimes",
- "middleware",
- "adapters",
- "red hat",
- "jboss",
- "wildfly",
- "minishift",
- "container development kit",
- "cdk",
- "enterprise application platform",
- "eap"

![image](https://user-images.githubusercontent.com/49404737/62447357-7f7d2a80-b765-11e9-9dcb-16ceadd8ee1b.png)
