### ISSUE TITLE
Error retrieving an empty port if working with more than one rsp provider

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-server-connector#400]
I'm currently working with 2 rsp providers (Red Hat (widfly/crc/...) and Extras (tomcat/felix)) and the port returned by portfinder.getPortPromise(); is the same for both (8002). It results in having 2 nodes (in the tree) that point to the same rsp and so i see the same servers twice.

**Comment by lstocchi** [comment]
we agreed at explicitly declaring a range where portfinder can search for a port in each connector - https://github.com/robstryker/rsp-server-extras/pull/4/files

**Comment by robstryker** [comment]
It'd be a good idea to allocate a similar range for this extension as well?
