### ISSUE TITLE
EAP/WF server adapter's custom socket binding to different port is not taken into account when "Show In Browser"

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-server-connector#408]
I changed custom http port for the server in EAP 7.1 edit Server option (8080->8888). when the adapter is started Show In browser action keeps pointing to 8080 port.

**Comment by lstocchi** [comment]
@odockal You also have to change the port in the server's standalone.xml file. I just tried with EAP and it worked for me. Let me know if this still happen to you.
We also added a faq https://github.com/redhat-developer/vscode-server-connector#2-can-i-run-my-wildfly-server-on-a-different-port-than-the-default-one XD

**Comment by robstryker** [comment]
Something tells me both steps shouldn't be required.  I'll have to investigate this.

**Comment by robstryker** [comment]
Fixed in FAQ. We could maybe inspect config file if people haven't changed it manually in the server, but that'd be a feature request.
