### ISSUE TITLE
Run task before debugging the server

### ISSUE THREAD

**Issue by rsrocha83** [redhat-developer/vscode-server-connector#416]
Is it possible to run a command or task before starting/debugging the server? Something like the property `preLaunchTask` in launch.json file.

I would like to automatically run `mvn package` on my project just before debugging the server to get the latest modifications in the code.

**Comment by robstryker** [comment]
Not at this time.  We can look into it I guess, but would need to figure out where it'd be appropriate.

**Comment by rsrocha83** [comment]
Allowing to define a launch.json, or something similar, for debugging the server would be great. For example, Debugger for Java extension allows step filtering through launch.json. I also miss this functionality while debugging with server connector.

**Comment by robstryker** [comment]
This is not on the roadmap.

**Comment by ztrnr** [comment]
Any chance this would be revisited? Utilizing Launch configurations streamlines workflows.
