### ISSUE TITLE
Canceling addDeployment operation throws an error

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-server-connector#418]
1. Create a server using RSP
2. Start the server
3. Ctx menu on server-> Add deployment
4. Input box is opened, offers file or exploded deployment
5. Click somewhere in the IDE to cancel the operation
6. Assert: operation is canceled
Actually it is canceled but error pops up:
```
Error running command server.addDeployment: Cannot read property 'hasOwnProperty' of undefined. This is likely caused by the extension that contributes server.addDeployment.
```

**Comment by lstocchi** [comment]
Good catch... we checked if user wasn't picking anything but we returned no error message. It should be fixed by https://github.com/redhat-developer/vscode-rsp-ui/pull/99
