### ISSUE TITLE
README does not mention EAP 7.3 support

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-server-connector#419]

**Comment by robstryker** [comment]
It doesn't mention it bc we don't support it lol.  
Seems even though its available in stacks.yaml, it uses `wtp-runtime-type: org.jboss.ide.eclipse.as.runtime.eap.73` and we don't have that runtime type declared. So... guess we need to add it.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/528
