### ISSUE TITLE
Bad server labelling

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-server-connector#425]
I noticed that EAP servers are labelled JBoss EAP xxx. I think we should rename them as Red Hat EAP xxx.
Also EAP 7.3 is listed but EAP 7.3 is not yet GA so we should add a Preview or Beta qualifier

**Comment by robstryker** [comment]
It's a good idea, but, if you check https://www.redhat.com/en/technologies/jboss-middleware/application-platform    it seems they use "JBoss EAP" more often than "Red Hat JBoss EAP".  If we want confirmation here, we should ask the EAP team which name is most appropriate, and (if Red Hat is most appropriate) when they switched to that?  We wouldn't want to (for example) rename JBoss 4.3 to "Red Hat JBoss 4.3". 

I'm also concerned that we might eventually add an IBM to it ;)   "IBM Red Hat JBoss EAP" starts to get a bit ridiculous =P 

+1 for tech preview though

**Comment by jeffmaury** [comment]
https://developers.redhat.com/products/eap/overview

**Comment by robstryker** [comment]
Not sure I see your point. The first paragraph reads:

 Overview

JBoss EAP is an open source platform for highly transactional, web-scale Java applications. EAP combines the familiar and popular Jakarta EE specifications with the latest technologies, like Microprofile, to modernize your applications from traditional Java EE into the new world of DevOps, cloud, containers, and microservices.

Note the lack of "Red Hat".

**Comment by jeffmaury** [comment]
Look at the main title and see the logo:

![EAP](https://developers.redhat.com/sites/default/files/eap-logo.png)

**Comment by robstryker** [comment]
Um... yeah I see that. My point is it's not used as often. 

So far you provided 1 link, where "JBoss EAP" and "Red Hat JBoss EAP" were both used once each. I provided a link where "JBoss EAP" was used several times and "Red Hat JBoss EAP" was used only once.

I believe my point still stands.

**Comment by jeffmaury** [comment]
I think the main title rules and the logo, it's not being repeted like the CodeReady Studio docs where title has Red Hat CodeReady Studio and the rest of the text uses CodeReady Studio or CRS.

**Comment by robstryker** [comment]
issue replicated in JBT.  

window -> preferences -> JBoss Tools / JBoss Runtime Detection -> click download button. 

This is a problem in stacks.yaml and should be fixed there.

**Comment by robstryker** [comment]
![vscode-server-connector_issue425](https://user-images.githubusercontent.com/630383/75908505-43539a80-5e18-11ea-87f6-7d45c372390b.png)

**Comment by robstryker** [comment]
https://github.com/jboss-developer/jboss-stacks/pull/132

**Comment by robstryker** [comment]
Should be fixed now jboss-developer/jboss-stacks#132
