### ISSUE TITLE
Widlfly not starting when added manually ("on disk")

### ISSUE THREAD

**Issue by flash-me** [redhat-developer/vscode-server-connector#427]
Hey folks,

when using the prompts to download a wildfly server, it will be located at `%HOME%\.rsp\redhat-server-connector\runtimes\installations` on Windows by default.

So for Wildfly 19 the full path is `%HOME%\.rsp\redhat-server-connector\runtimes\installations\wildfly-1900finalruntime\wildfly-19.0.0.Final`

Previously I already downloaded a wildfly package in placed it to `C:\\sources`.
When trying to start, I will get following alert: 
![image](https://user-images.githubusercontent.com/5240450/78450516-56f45a00-767f-11ea-8250-c63b82f1b32d.png)

#### Interesting part
When I **move** the folder from `C:\\sources` to `%HOME%\.rsp\redhat-server-connector\runtimes\installations\wildfly-1900finalruntime\`  **everyhting works**

The content of my server config which has been created by the plugin:
```
{
  "args.override.boolean": "false",
  "args.program.override.string": "-mp \"c:\\sources\\wildfly-19.0.0.Final\\modules\" -jaxpmodule javax.xml.jaxp-provider -jaxpmodule javax.xml.jaxp-provider org.jboss.as.standalone --server-config=standalone.xml",
  "args.vm.override.string": "\"-Dprogram.name=rsp:wf-11\" -server -Xms1303m -Xmx1303m -XX:MaxPermSize=256m -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true \"-Dorg.jboss.boot.log.file=c:\\sources\\wildfly-19.0.0.Final\\standalone\\log\\boot.log\" \"-Dlogging.configuration=file:c:\\sources\\wildfly-19.0.0.Final\\standalone\\configuration\\logging.properties\" \"-Djboss.home.dir=c:\\sources\\wildfly-19.0.0.Final\" ",
  "id": "wf-11",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.eap.60",
  "server.home.dir": "c:\\sources\\wildfly-19.0.0.Final",
  "wildfly.publish.restart.pattern": "\\.class$|\\.jar$"
}
```

#### My question
Is it required to place the wildfly folder under `%HOME%\.rsp\redhat-server-connector\runtimes\installations\wildfly-1900finalruntime\` 

cheers
flash :zap:

**Comment by flash-me** [comment]
Also, if using to plugins to download a widlfly, following server config will be created:
```
{
  "args.override.boolean": "false",
  "args.program.override.string": "-mp \"%HOME%\\.rsp\\redhat-server-connector\\runtimes\\installations\\wildfly-1900finalruntime\\wildfly-19.0.0.Final\\modules\" org.jboss.as.standalone --server-config=standalone.xml",
  "args.vm.override.string": "\"-Dprogram.name=rsp:wildfly-19.0.0.Final\" -server -Xms64m -Xmx512m -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true \"-Dorg.jboss.boot.log.file=%HOME%\\.rsp\\redhat-server-connector\\runtimes\\installations\\wildfly-1900finalruntime\\wildfly-19.0.0.Final\\standalone\\log\\boot.log\" \"-Dlogging.configuration=file:%HOME%\\.rsp\\redhat-server-connector\\runtimes\\installations\\wildfly-1900finalruntime\\wildfly-19.0.0.Final\\standalone\\configuration\\logging.properties\" \"-Djboss.home.dir=%HOME%\\.rsp\\redhat-server-connector\\runtimes\\installations\\wildfly-1900finalruntime\\wildfly-19.0.0.Final\" -Dorg.jboss.logmanager.nocolor=true -Djboss.bind.address.management=localhost --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED --add-modules=java.se",
  "id": "wildfly-19.0.0.Final",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.wildfly.190",
  "server.home.dir": %HOME%\\.rsp\\redhat-server-connector\\runtimes\\installations\\wildfly-1900finalruntime\\wildfly-19.0.0.Final",
  "wildfly.publish.restart.pattern": "\\.class$|\\.jar$"
}
```

Which is different when adding a already downloaded wildfly folder. Why though?

cheers
flash :zap:

**Comment by lstocchi** [comment]
Hi @flash-me , no it's not required to move the folder. It should work.

I made a quick test right now and i didn't have any issue with it.
Downloaded wf19 from https://download.jboss.org/wildfly/19.0.0.Final/wildfly-19.0.0.Final.zip and
 created new server pointing to the unzipped folder.

This is my config

```
{
  "args.override.boolean": "false",
  "args.program.override.string": "-mp \"c:\\Users\\Luca\\Downloads\\wildfly-19.0.0.Final\\wildfly-19.0.0.Final\\modules\" -jaxpmodule javax.xml.jaxp-provider -jaxpmodule javax.xml.jaxp-provider org.jboss.as.standalone --server-config=standalone.xml",
  "args.vm.override.string": "\"-Dprogram.name=rsp:wf-11\" -server -Xms1303m -Xmx1303m -XX:MaxPermSize=256m -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true \"-Dorg.jboss.boot.log.file=c:\\Users\\Luca\\Downloads\\wildfly-19.0.0.Final\\wildfly-19.0.0.Final\\standalone\\log\\boot.log\" \"-Dlogging.configuration=file:c:\\Users\\Luca\\Downloads\\wildfly-19.0.0.Final\\wildfly-19.0.0.Final\\standalone\\configuration\\logging.properties\" \"-Djboss.home.dir=c:\\Users\\Luca\\Downloads\\wildfly-19.0.0.Final\\wildfly-19.0.0.Final\" ",
  "id": "wf-11",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.eap.60",
  "server.home.dir": "c:\\Users\\Luca\\Downloads\\wildfly-19.0.0.Final\\wildfly-19.0.0.Final",
  "wildfly.publish.restart.pattern": "\\.class$|\\.jar$"
}
```

There is an error with the type and we will verify that but the server should start. Have you downloaded the correct wf19 package? Have you verified the path is the correct one (i mean, in my case i have two wildfly-19.0.0.Final folder)?

**Comment by flash-me** [comment]
Hi @lstocchi 

VsCode:
![image](https://user-images.githubusercontent.com/5240450/78472700-37bb0280-773b-11ea-8a2f-93b26c97d79c.png)

Terminal:
![image](https://user-images.githubusercontent.com/5240450/78472707-47d2e200-773b-11ea-876b-a6f33fc83097.png)

How can the Java Version be the problem? On both paths I'm using the same Java SDK, I'm just switching the wildfly path between default and `c:\\sources\\`

cheers
flash :zap:

**Comment by flash-me** [comment]
Ok this is really weird and I'm pretty sure its not because of the Java Version.
Just recorded a video off it:
https://drive.google.com/open?id=1GnwXgGTb_tPaYpYQte3VP4x88W8utI2G

cheers
flash :zap:

**Comment by lstocchi** [comment]
Weird... i'm not able to replicate it even by doing what you did in your video. @robstryker any idea?

**Comment by flash-me** [comment]
Successfully tried same scenario with Manjaro Kyria 19.0.2 with XFCE and Java 1.8.0_242. 

cheers
flash :zap:

**Comment by robstryker** [comment]
In the video, I notice one of the editors has property org.jboss.tools.rsp.server.typeId="org.jboss.ide.eclipse.as.eap.60".  If you are creating a server (whether downloaded or from disk) and it is recognizing a wf19 as an eap60, then that is a bug and needs to be fixed. 

What's going on in the back end is that we restrict the javas that may be used with a server type to ones that we know are compatible.  EAP 60 for example is only runnable with java6 through java8.  

This bug rings a bell in my mind. It seems wf19 support was added to rsp and jbosstools at the same time, and the original impl had a problem. It seems it was fixed in jbt:  https://github.com/jbosstools/jbosstools-server/commit/abfd4b58f3935dcababf98abd03c96636be2c9c6    

I'll need to double-check this. It's definitely mis-identifying a wf19 as an eap60. 

Good catch, guy.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/556

**Comment by robstryker** [comment]
redhat-developer/rsp-server#556  was merged and this issue should be fixed. Anyone care to verify?

**Comment by flash-me** [comment]
> [redhat-developer/rsp-server#556](https://github.com/redhat-developer/rsp-server/pull/556) was merged and this issue should be fixed. Anyone care to verify?

I'll try it and give you feedback 

cheers 
flash :zap:

**Comment by flash-me** [comment]
Tried it out and it works. Good job.
Setup:
Windows 10 (19041.153)
VsCode 1.44.0
Server Connector 0.20.0
Remote Server Protocol UI 0.15.3
Wildfly 19

cheers 
flash :zap:

**Comment by goldammer** [comment]
I can also confirm that the local Wildlfy 19, that was previously identified as eap60 is now correctly shown as Wildfly 19.

Thanks!

**Comment by robstryker** [comment]
Thank you all for helping us out and finding these bugs. It's really great to have a community of users willing to participate in making our tools better.
