### ISSUE TITLE
Terminating RSP provider wont kill the process

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-server-connector#432]
1. Have RSP running
2. Terminate it
3. ASSERT: RSP is stopped - ok
4. ASSERT: RSP process is gone - fail: process is still alive and one cannot start RSP over, it says:
```
Unable to start the server: Extension backend error - rsp error - red hat server connector failed to start - workspace is locked. please verify workspace is not in use
```

Workaround: Kill rsp process manually. Then one can start rsp provider again.

**Comment by robstryker** [comment]
Please give more explanation as to how you are terminating it. Are you using the vscode UI to shut it down? Or are you kill -9 the process?

If you are kill -9 the process, there is absolutely no way for me to interrupt that and ensure all server adapters are shut down.

**Comment by robstryker** [comment]
I need more explanation here. I'm quite confused.

**Comment by odockal** [comment]
Sure, sorry. By terminating here, I mean RSP server provider context menu option - Terminate RSP Provider, available while rsp is started.

**Comment by robstryker** [comment]
opened https://github.com/redhat-developer/vscode-server-connector/pull/434 and https://github.com/redhat-developer/rsp-server-community/pull/23  

Stupid mistakes.

**Comment by robstryker** [comment]
Both PRs closed / merged

**Comment by odockal** [comment]
Noice! Thanks!
