### ISSUE TITLE
Restrict context menu items over server adapter to avoid confusion

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-server-connector#454]
It is possible to add deployments and calls server action over stopped server adapter. This might lead to a confusions, as image this use case:

1. Have WF server started
2. Have EAP server stopped
3. Call server action show in browser for localhost:8080 on EAP server
One gets WF localhost index content.
4. Add deployment to the EAP (stopped)
5. Show in browser -> chosen deployment
One gets 404

**Comment by robstryker2** [comment]
We should not disable "server actions" if server is stopped. Many server actions may be valid (edit config file) when server is stopped. 

We should trust our users to realize they have several servers configured on the same machine. They should be able to figure this out. 

If possible, we can consider hiding the show-in-browser actions if the server is stopped. But I see this as an optional enhancement, not a bug. Users should be able to navigate their own workspaces here.
