### ISSUE TITLE
Run different Java version than was used to start Visual Studio Code

### ISSUE THREAD

**Issue by ryno1234** [redhat-developer/vscode-server-connector#458]
The new minimum required Java version for the Red Hat Language Support is Java 11. By upgrading to Java 11, I essentially break my ability to run Wildfly 12 through the Server Connector tool because Wildfly 12 does not run on Java 11 (at least according to the UI, because I can run Wildfly 12 using Java 11 from the command prompt).

I get the following error text when attempting to start the server:

_Unable to start the server:  Extension backend error - server can not be started: server wildfly is not compatible with discovered java version 11.0.7_

**Comment by lstocchi** [comment]
Thanks for reporting this @ryno1234 . There is a server property "vm.install.path" that allows to specify the location of a different java home but we found out it is not working correctly as before. Once we fix that you should be able to use that property and run your Wildfly instance as before. I'll let you know when we have a fix. Thank you and sorry for the inconvenience.

**Comment by lstocchi** [comment]
@ryno1234 the new server connector extension (0.23.3) was released so now you can make a single server uses a different java.home (you should be able to use it in conjuction with the latest vscode java). 

Just right click to the server -> edit server -> add `"vm.install.path": "path/to/your/java8"` and save. Now it should work fine. Let us know if you face any other issue. Thank you and sorry for taking so long.

**Comment by ryno1234** [comment]
@lstocchi, thank you! I would consider this a VERY quick turnaround on a request. Much appreciated.
