### ISSUE TITLE
Community Server Connector "starting" then stops after 30-60 seconds

### ISSUE THREAD

**Issue by latcomsystems** [redhat-developer/vscode-server-connector#468]
This started happening in the last two weeks.  Everything worked fine before.

These are the last lines of log output:

16-Sep-2020 08:53:09.105 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
16-Sep-2020 08:53:09.114 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
16-Sep-2020 08:53:09.117 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [89,501] milliseconds

Nothing after that.  I can use the server for less than a minute, then it stops.  Status goes to "starting", then eventually "stopped".  Never gets to fully "started".

**Comment by latcomsystems** [comment]
![image](https://user-images.githubusercontent.com/16857503/93340884-6f0a0100-f7fb-11ea-9f52-b60c7051f532.png)

![image](https://user-images.githubusercontent.com/16857503/93340962-88ab4880-f7fb-11ea-8a29-4e189d4f00ec.png)

![image](https://user-images.githubusercontent.com/16857503/93341188-c9a35d00-f7fb-11ea-9702-3e4cfc64e930.png)

**Comment by latcomsystems** [comment]
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Name: Community Server Connectors
Id: redhat.vscode-community-server-connector
Description: Connects vscode with open source community-driven servers and runtimes.
Version: 0.23.3
Publisher: Red Hat
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-community-server-connector

**Comment by robstryker** [comment]
So there are two issues here.  First is the two minute timeout. The timeout can now be configured as per https://github.com/redhat-developer/rsp-server/issues/587    In short, if you edit the server and add a flag like "server.timeout.startup": "120000"  you can override the number to any number of miliseconds you want. 

But obviously that's not the important issue here. Your issue is that polling seems to fail no matter what. To determine if the server is up or down, we make an http request at host:port so for example http://localhost:8080  or similar to see what the response is. If you have a different port in use, you may need to override that setting, also by editing the server, and adding a field like "server.http.port": "9000" or whatever port you want. 

If you are pretty sure your server is running on port 8080, and is binding to localhost, then test it in a web browser. We only check http://localhost:${server.http.port}  to see if an http response is provided. If you've changed the host, well, we don't have a way to override that part for tomcat just yet. It's an oversight on our part. 

Did you change the host? Do we need to check a particular IP address or similar?

**Comment by latcomsystems** [comment]
Thank you for your response Rob!

I'm 100% positive the port is still 8080.  Nothing has changed on the application side since the last time this setup worked, which was about two months ago.  The only difference is a couple of VSCODE and plugin updates since then.
I can actually use the web app in the browser for a minute or two after the log shows "Server startup in xxxxx milliseconds" (see the screenshot above).  The status in the left panel still shows "starting..." at this point.  A minute or two later, the status changes to "stopped", nothing new shows up in the console log, and the web app stops working - no more responses from server on 8080.

I can try fiddling with the timeout setting, but won't get to it until Monday.

**Comment by robstryker** [comment]
Fiddling with the timeout won't actually fix anything ;)  Our app still must be trying to access http://localhost:8080

Are you 100% sure your tomcat server is started bound to "localhost" and not an IP address? What do you type in your web browser to view your app?

**Comment by latcomsystems** [comment]
Yep, 100% sure it's localhost.

This is when the server is "starting":

![image](https://user-images.githubusercontent.com/16857503/93671033-b7c8f080-fa6d-11ea-9ab5-ae9ce47d5c01.png)

And this is when it stops after about a minute:

![image](https://user-images.githubusercontent.com/16857503/93671049-dc24cd00-fa6d-11ea-9286-01dce32c9696.png)

**Comment by latcomsystems** [comment]
If you have some time during the week, I would be more than happy to do a quick Google Meet and a screen share to demonstrate this if that would be helpful.

**Comment by latcomsystems** [comment]
Here are some logs that show the server starting up, and the browser accessing it.  Nothing in here about why it shuts down unexpectedly.
[localhost_access_log.2020-09-19.txt](https://github.com/redhat-developer/vscode-server-connector/files/5250137/localhost_access_log.2020-09-19.txt)
[catalina.2020-09-19.log](https://github.com/redhat-developer/vscode-server-connector/files/5250138/catalina.2020-09-19.log)
[localhost.2020-09-19.log](https://github.com/redhat-developer/vscode-server-connector/files/5250140/localhost.2020-09-19.log)

**Comment by latcomsystems** [comment]
This is http://loalhost:8080
![image](https://user-images.githubusercontent.com/16857503/93779485-0fde2f00-fbf5-11ea-8525-c2ab0c844c5d.png)

**Comment by latcomsystems** [comment]
And here is the network inspector in the browser, all returning 200 until the server shuts down about a minute later.
![image](https://user-images.githubusercontent.com/16857503/93780010-a01c7400-fbf5-11ea-81d1-b05444068d2e.png)

**Comment by latcomsystems** [comment]
I have some news.  I was able to resolve my problem by setting up a new tomcat server version 8.5.50 through the connector and everything is working.  Looks like tomcat 9.0.30 is the problem.  I remember, the original setup that worked was 9.0.27 and there were no issues.  One of the VSCODE updates updated the server to 9.0.30 and that is when I believe the problem started.
So, for now, I'm all set with version 8.5.

**Comment by robstryker** [comment]
That's still very weird but I'm glad to hear the connector is working again. 
I'll close this as not_rsp I guess...  But if it happens again or with another version you should re-open this bug.

**Comment by VitalyVaryvdin** [comment]
Happens at my end with Wildfly 25
I can freely access server via browser at localhost:8080 but still stuck at "Starting" state
{
    "jboss.server.host": "localhost",
    "jboss.server.port": "8080"
}
