### ISSUE TITLE
Not possible disable output console focus.

### ISSUE THREAD

**Issue by DaniloOC** [redhat-developer/vscode-server-connector#481]
Always wich have a new log in output tab the focus change for him, not allowing to use the code editor.

Video with what happens:
[output-change-focus (2).zip](https://github.com/redhat-developer/vscode-server-connector/files/5953300/output-change-focus.2.zip)

Issue for vscode: https://github.com/microsoft/vscode/issues/116107

**Comment by robstryker** [comment]
![image](https://user-images.githubusercontent.com/630383/107414524-1f94dc00-6ae0-11eb-9547-c69cf2d2752a.png)

You can go to preferences -> Servers View  and uncheck the box "Show Server's output channel when new text added to output stream."

**Comment by DaniloOC** [comment]
Thanks, it worked.
