### ISSUE TITLE
Contextual action "Edit server" doesn't work anymore

### ISSUE THREAD

**Issue by sliw39** [redhat-developer/vscode-server-connector#485]
When I try to show the JSON configuration of my server,
Right-click your server -> Edit Server 

Nothing happens. I've checked the log stderr, but it is empty.
The other actions are working fine

Does anyone has this issue ? Is there another way to update those files ? 
Thanks

**Comment by sliw39** [comment]
I reverted the plugin back to 0.22 but I sill have the issue. It seems more vscode related

**Comment by odockal** [comment]
@sliw39 I believe that this was fixed in https://github.com/redhat-developer/vscode-rsp-ui/pull/164. Though we have not released it yet. 

Fastest option is to build it locally (`npm i`, `npm build`, `vsce package`) and install from vsix or wait a while (days probably) so we can release it.

**Comment by sliw39** [comment]
@odockal Thanks I'll try it next week
