### ISSUE TITLE
Watching expression when debugging Wildly server

### ISSUE THREAD

**Issue by AlEmerich** [redhat-developer/vscode-server-connector#513]
Hello,

I succeeded install Wildlfy 8 server and debugging is working (code stop at breaking, variable correctly evaluated, ...) but not the watch expression. When I want to evaluate some expression, VSCode give the following error message: 
![image](https://user-images.githubusercontent.com/12711720/131875551-b2481078-c241-4c2a-9606-1d2b9cc175dc.png)

Do you have any idea how I can configure the launch.json to make it work ? 

PS: The following obvious config does not work:

![image](https://user-images.githubusercontent.com/12711720/131876225-d6ab5e5c-cb04-4ca8-89d6-17baefbca82e.png)

**Comment by robstryker** [comment]
We've had users complain about this before:   https://github.com/redhat-developer/rsp-server-community/issues/85#issuecomment-797222351

there seems to be some issues outside of our project causing this, and some of the suggestions here seem to make things work better.

**Comment by robstryker** [comment]
Closing as a duplicate to https://github.com/redhat-developer/rsp-server-community/issues/85
