### ISSUE TITLE
Problem with vm args for a JBoss EAP 7.1.0

### ISSUE THREAD

**Issue by leonix94** [redhat-developer/vscode-server-connector#519]
Hi, I've a problem with an istance of a JBoss EAP 7.1.0.GA (WildFly Core 3.0.10.Final-redhat-1) and your plugin.

Unfortunately all my vm args are not working on the startup launch configuration. I add the same string used in the eclipse plugin too after the "args.program.override.string" argument in the xml file opened after clicked on Edit Server.

The server start properly and the software deployed but some arguments needed aren't loaded.

**Comment by hoffm473** [comment]
You must set args.override.boolean to true in order for the other args.override properties to be applied.

**Comment by leonix94** [comment]
I've already set it on true

**Comment by leonix94** [comment]
```
"args.override.boolean": "true",
  
"args.program.override.string": "-mp \"c:/jboss-eap-7.1-Gded/modules\" org.jboss.as.standalone -b localhost -server-config=standalone.xml -Dswa.properties=\"C:/dev/samplea.properties\" -Dswb.properties=\"C:/dev/sampleb.properties\" "

```

i tried putting those args in different ways (with or without "", with \ or /...everything) but it doesn't load the properties file there

**Comment by robstryker** [comment]
Once the process is launched, have you verified that the process was actually launched with the correct arguments? You should be able to see this in the task manager.

**Comment by leonix94** [comment]
using wmic.exe path Win32_Process where handle='****' get Commandline /format:list 

I can confirm they're correctly loaded. I'm using the same args present in the eclipse plugin (fixing the //)

**Comment by robstryker** [comment]
Oh! I should have noticed this before. We have a different flag for vm args! 
"args.program.override.string" is for program arguments.
"args.vm.override.string" is for VM arguments. 

Try this! I hope it helps!

**Comment by robstryker** [comment]
Closing issue!
