### ISSUE TITLE
The extension aggressively calls the reveal output causing autoswitch to the output window

### ISSUE THREAD

**Issue by CadenScharpf** [redhat-developer/vscode-server-connector#525]
Running the server from the extension basically renders the integrated terminal useless because the window automatically switch back to the server output every time something is logged. I believe there to be a similar cause to this issue submitted to the developers for the php language server: https://github.com/felixfbecker/php-language-server/issues/761

**Comment by robstryker** [comment]
![image](https://user-images.githubusercontent.com/630383/159304375-6b94eed1-86ff-466d-bcc9-f24afe7942f6.png)

I've just tested this and it seems to work as expected.
