### ISSUE TITLE
Allow multiple configurations per server installation

### ISSUE THREAD

**Issue by tarkin67** [redhat-developer/vscode-server-connector#530]
In our Wildfly setup we have multiple domain configurations per wildfly installation. The directory structure is the following:

`%WILDFLY_HOME%\user_projects\domains\<domain_name>\configuration\standalone.xml`
![image](https://user-images.githubusercontent.com/14755478/156980321-12bd22d7-ad9c-473c-a0cd-3bd1fef2695e.png)

With this setup the vscode-server-connector is basically useless, since it only allows for configuration files that are located within the `%WILDFLY_HOME%\configuration` directory.

The Wildfly server adaptor for Eclipse handles this much more elegantly by allowing to set a server home dir as well as a server base directory:
![image](https://user-images.githubusercontent.com/14755478/156980690-0ecfa96d-4dc7-4711-90a3-f75c3c1d3bb9.png)

It would be great to have something similar to this with the vscode-server-connector.

Please let us know your thoughts on this!

**Comment by liechtir** [comment]
Agree, same issue here.

**Comment by liechtir** [comment]
hi, any new on this? @robstryker @odockal @jrichter1

**Comment by tarkin67** [comment]
Hi, any news? @robstryker @odockal @jrichter1

**Comment by 99sono** [comment]
Hi There,

Yes, this feature is quite important. 
The wildly plugin deployment for eclipse does this very nicely.

In eclipse, we can have for each our projects a specific domain/stand alone folder.
Within it, we have the standalone.xml configuration with the (port, queues, data sources, jta transaction timeout, etc...) that is appropriate for the specific project.
Having a single standalone directory with multiple configuration files is not a good approach.

Please consider making sure that the features of the vscode plugin are on pair with the configuration possibilities of eclipse. 

My recommendation would be to consider the wildfly plugin for eclipse as the gold standard.
Any aspect that eclipse allows to tune (e.g. lunch parameters, standalone folder location, configuration file within the folder, etc...).
Many thanks for having a look at this issue.

Kindest regards.

**Comment by robstryker** [comment]
Sorry, I was on parental leave. I'll try to dig in deeper as soon as I get settled.

**Comment by liechtir** [comment]
@robstryker congrats to the new dev in the team!
did you find anything?

**Comment by roiabanca** [comment]
Is there any advance in this issue? In order to use vscode in an enterprise this functionallity must be inplemented

**Comment by robstryker** [comment]
I merged it into rsp-server repo but not sure when I'll get a release done. 

https://github.com/redhat-developer/rsp-server/pull/717
