### ISSUE TITLE
Unable to create the server: Extension backend error - there are no rsp providers to choose from.

### ISSUE THREAD

**Issue by DuLima** [redhat-developer/vscode-server-connector#532]
I don't know if you can help me or not. 
I get this error when I try to create a server.

**Comment by zhang-guanghao** [comment]
How to fix it?

**Comment by lstocchi** [comment]
Hi guys, what are you doing exactly? Which is your OS? Vscode/plugin version? 
Do you see something like the image below? Did you start the rsp connector (right click on a node and click on `Start/ Connect to RSP Provider)? Without any info it's hard to guess the problem. Thanks
![image](https://user-images.githubusercontent.com/49404737/175799345-047274d0-7a90-4aa0-ad08-cee7a55fdadc.png)

**Comment by robstryker** [comment]
If you guys could share details like @lstocchi  asked, including java version, that'd be very helpful.

**Comment by ila-embsys** [comment]
I have looked to the developer tools and noticed the the extension show an error related to the JAVA_HOME variable. Since it was set correctly I have looked through the extension source code and found that the extension wants to find 'javac' binary. So I have resolved the issue by installing java developer package. E.g. java-11-openjdk-devel.

**Comment by robstryker** [comment]
Hrmm.  I'm going to leave this issue open for a bit so I can think how to get better error messaging here.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/vscode-rsp-ui/commit/53b4ed03577b33b128eeb021bc6187166fd47b1e

https://github.com/redhat-developer/vscode-server-connector/commit/7d5a48356b4029161cee99b93de4b410b0416763

https://github.com/redhat-developer/rsp-server-community/commit/8b2b29632b4397a7001c94365fd83a9d2722b232

Three commits to make the error message more clear about what's missing.
