### ISSUE TITLE
What are the differences between Community Server connector and Server Connector

### ISSUE THREAD

**Issue by Osolemio44** [redhat-developer/vscode-server-connector#537]
Hello. As a novice programmer using Java in Vscode I have wondered what are the differences between the `Community Server Connector` and the `Server Connector` as they both seem to do the same thing at the same cost.
I've searched the issues for information on this topic, but haven't found anything.

**Comment by robstryker** [comment]
The Community Server Connector is a slimmed down installation that provides community-level (ie not enterprise level) support and is for servers / runtimes that Red Hat is not in the business of supporting in any real way, like apache projects or other freely available servers. Also the implementations of these are a little bit more basic, less details, less flexibility, and are mostly just like, a good generic tool for users. 

The Server Connector provides the same functionality for Red Hat projects and products, like WildFly, EAP, CDK, minishift, etc, but we go out of our way to make things as comfortable as humanly possible, provide more options, more overrides, and the code to maintain it is significantly heavier. 

From a user's perspective, though, the community edition is for projects we don't own, and the Server Connector is for "our apps"

Hope this helps!
