### ISSUE TITLE
[Question] How to add a remotely managed jboss/wildfly 

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-server-connector#538]
In Eclipse Jboss Tools you could add a remotely managed server instance into Eclipse and deploy artifact into it. How to achieve the same with this vscode extension ?

**Comment by robstryker** [comment]
The eclipse plugins depended on a set of plugins called RSE (Remote System Explorer) to do a lot of this dirty work. Those plugins are big, complicated, and no longer maintained. Porting them into the server connector framework would be hard and likely a huge boondoggle, considering their codebase is very eclipse specific, extendable to a fault (ie so extendable that much of the code is needless abstractions), and we may be better off supporting a single protocol and doing it from scratch or with the aid of a more widely used library. 

The short answer is, no, we don't have that support right now. But, some users have found luck by doing things like creating a "server adapter" who's home directory is a folder that is actually, on the OS level, a remote system mounted via sshfs or similar.

**Comment by gayanper** [comment]
So you mean the eclipse jboss plugins will be not updated frequently anymore and vscode plugins will be more prioritize and will get this feature in a future release is it ?
So if i focus on working with java, jboss I should focus on using vscode if i need upto date plugin support ?

**Comment by gayanper** [comment]
Thanks @robstryker

**Comment by robstryker** [comment]
I've opened https://github.com/redhat-developer/vscode-server-connector/issues/547   to track the issue.
