### ISSUE TITLE
Wildfly 26.1.1 doesn't launch with Java 17

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-server-connector#549]
Even though it's actually compatible (see https://www.wildfly.org/news/2022/04/14/WildFly261-Final-Released/), WF 26.1.1 doesn't launch with Java 17

<img width="648" alt="Screenshot 2022-07-27 at 18 12 35" src="https://user-images.githubusercontent.com/148698/181298001-d3f34b44-6664-4d67-917f-84dbaec7d996.png">

**Comment by robstryker** [comment]
Fixed with https://github.com/redhat-developer/rsp-server/commit/558a815701fdeea1626b885305804e29ec033dbc

Not yet released
