### ISSUE TITLE
oneOf validation of keys using "required"

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-server-connector#553]

**Comment by robstryker** [comment]
Um... can you elaborate on this issue? I'm not at all sure what it means.

**Comment by msivasubramaniaan** [comment]
@robstryker 

Actually this bug needs to be created on [YAML LS](https://github.com/redhat-developer/yaml-language-server) board, seriously I don't know how I created on here. Really sorry and for it and regret the inconvenience. Closing this issue.
