### ISSUE TITLE
Support of Maven Multi Module Project

### ISSUE THREAD

**Issue by markusarnold** [redhat-developer/vscode-server-connector#562]
Dear Support Team,

I am desperately trying to deploy a multi module maven JBoss EAP 7.3 project. I start to wonder whether this is supported at all ?
To be clear with "multi module maven" I mean a project, where in the main pom.xml there are other modules defined like:
<modules>
        <module>module1</module>
        <module>module2</module>
 </modules>

Any help or insight would be greatly appreciated
Thank You
Markus

**Comment by robstryker** [comment]
I'd need to see the project to even begin to understand how you are trying to publish it. 
Does the project produce several distinct outputs (for example, 1 ejb jar, 2 wars, and maybe some other resource) or does it output a single resource (like a .ear file) ?

**Comment by markusarnold** [comment]
Thanks for asking. The problem is not relevant to me any more, since I stopped working on it. I will close the issue.
