### ISSUE TITLE
Issue when adding WildFly server

### ISSUE THREAD

**Issue by worksofliam** [redhat-developer/vscode-server-connector#575]
Hi

I am getting this after selecting my Wildfly installation directory when adding a server.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/3708366/223757830-7b3fa6a8-4d42-474d-a7d0-9312b68b644e.png">

* VS Code 1.76
* Mac
* Server Connector 0.26.1

I have this in my configuration also:

```json
    "rsp-ui.rsp.java.home": "/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home"
```

**Comment by worksofliam** [comment]
Tried to downgrade to 0.25.6 and also removed the custom Java home with no luck.

Also, it would be useful if you folks had an output channel with more specific errors :) 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/3708366/223760121-47b11273-423f-4347-9b15-b9db0417ca90.png">

**Comment by worksofliam** [comment]
Got it working!

**Comment by robstryker** [comment]
Did you have to stay downgraded for it to work? Or does the newest version work for you?

**Comment by worksofliam** [comment]
@robstryker Had to stay downgraded. 

When I try to start the RHSC, I get this error on the latest version:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/3708366/227633327-db124697-b991-4ded-87c3-636caa6293d9.png">

**Comment by robstryker** [comment]
I'll be pushing updated error messaging and logic today. Let's see if this helps. Third time's a charm, right?

**Comment by worksofliam** [comment]
@robstryker Awesome - thank you!

I am very much enjoying this extension. Really streamlines my development.

**Comment by robstryker** [comment]
* 8f0fa53 - (HEAD -> master, origin/master, origin/HEAD) Test failure (22 hours ago) <Rob Stryker>
* 7870e1f - Fixes community issue 575 - error finding java (22 hours ago) <Rob Stryker>

Seems this was fixed here, but i referenced the wrong issue.
