### ISSUE TITLE
it would be nice if the OC cli would be added to the path

### ISSUE THREAD

**Issue by paule96** [redhat-developer/vscode-server-connector#577]
it would be nice if the OC cli would be added to the path, so it can be used in the terminal.

Currently I add the following configurations to my `.devcontainer.json` so I can use the CLI that comes with this extension:

```json
"remoteEnv": {
		// add oc cli to path
		"PATH": "${containerEnv:PATH}:/home/vscode/.vscode-server/extensions/redhat.vscode-openshift-connector-1.2.0-linux-x64/out/tools/linux"
	},
```

It would be nice if this extension would do it out of the box, or add a terminal profile that uses this path as default.

**Comment by paule96** [comment]
The sample in this issue, has also the problem if the version of the `redhat.vscode-openshift-connector` is changed, the line will break.

**Comment by robstryker** [comment]
Hi Maybe I'm a bit confused here. 

First, I'm not seeing any sample attached to this issue.  Second, this extension is unrelated to the `redhat.vscode-openshift-connector` extension. 

If you could walk me through the workflow you're attempting to use, that might clear it up?

**Comment by paule96** [comment]
Hi @robstryker ,

I men the following lines:

```json
"remoteEnv": {
		// add oc cli to path
		"PATH": "${containerEnv:PATH}:/home/vscode/.vscode-server/extensions/redhat.vscode-openshift-connector-1.2.0-linux-x64/out/tools/linux"
	},
```

But if it has nothing todo with this repo can me guide me to the correct repo? where is the code that is used by the extension `redhat.vscode-openshift-connector`?

**Comment by paule96** [comment]
I guess I found it. It is probably the repo here:
https://github.com/redhat-developer/vscode-openshift-tools

**Comment by paule96** [comment]
I will close this issue now here. Because this was the wrong place. Sorry for the troubles

**Comment by robstryker** [comment]
No worries! Just glad we got you to where you belong!
