### ISSUE TITLE
Cannot activate terminal tab when debuging 

### ISSUE THREAD

**Issue by lucian0c** [redhat-developer/vscode-server-connector#590]
Debugging a Tomcat project with log output to console, that are running on background  (multi threading) make imposible to select terminal tab it allways return to output tab on every click.
Whenever  you select terminal tab it returns to the output windows because it has to show the logs. The proper function would be to avoid selecting output tab automatic.

**Comment by robstryker** [comment]
Please uncheck the " Show Channel On Server Output"  box in your settings. 

![image](https://github.com/redhat-developer/vscode-server-connector/assets/630383/ccf81436-75b4-4ece-b065-8932fa69decc)

**Comment by robstryker** [comment]
Please re-open if this does not fix your problem.
