### ISSUE TITLE
Add support for Wildfly 29

### ISSUE THREAD

**Issue by CodeShakingSheep** [redhat-developer/vscode-server-connector#592]
Wildfly 29 has been released end of July. 
https://www.wildfly.org/news/2023/07/21/WildFly29-Released/

Would be great if I could choose it as server to download.

**Comment by fbricon** [comment]
@robstryker would it be possible for vscode-server-connector to fetch a remote config file, listing supported servers? It'd be easier to update the list without having to republish the extension every time

**Comment by CodeShakingSheep** [comment]
I just checked in VSCode and Wildfly 29 and 30 are available now which is great. Thanks.
