### ISSUE TITLE
WAR file changes isn't detected is it because it doesn't republish?

### ISSUE THREAD

**Issue by devanpedrik** [redhat-developer/vscode-server-connector#608]
I am running a maven project with SLF4J for wildfly 26. It seems that when I add LOGGER.info and such, it does not output the LOGGER into the console until I run the mvn clean install command on my project and restarting the server.

I have tried running wildfly with the same configuration on eclipse and the logger is shown in the console as expected so I don't think there are anything wrong with the SLF4J setup in the wildfly configuration. So I wonder if the server does not republish automatically like eclipse does and is that the supposed function for async publish provided in the setting. 

Process for clarity:
1. Add LOGGER.info("some text here"); then trigger the method containing the logger and it isn't shown in the console.
2. Restarting the server after it. Then trigger the method containing the logger again and it isn't shown in the console either.
3. Run mvn clean install command in the project then restart the server. Only then the logger is shown in the console. 

Other issue that I faced:
1. Clicking terminate server shows error popup that says the server is already stopped. Is this the expected behavior or am I missing some configuration for it? Seems to me that its not doing anything.
2. Clicking the add new server button provided in the view shows the quickpick options download or select from local but I found that if I just created a server then I tried to create it again, it would not work until I reload vscode via reload window. But right clicking then selecting create new server works fine.

Also some side question, 
1. How do I know if the async publish is working? It might be obvious but I can't see it in action which confuse me.

![image](https://github.com/redhat-developer/vscode-server-connector/assets/66743610/59018193-3dfd-4c6b-9e6b-e39740eafade)
In eclipse when you make changes to .java file it'll check module then create a new .war folder in the domain's deployment folder with the changes you just made to update it accordingly and this does not seems to be happening for vscode, which seem to be the cause for my problem. Unless I am missing some configuration for this.

![image](https://github.com/redhat-developer/vscode-server-connector/assets/66743610/ffb63e5f-8176-44d7-9cce-b747b4de57a4)
![image](https://github.com/redhat-developer/vscode-server-connector/assets/66743610/b41dfbfe-2fde-4b65-b2ef-8a7f0878a36e)

What actually happen for vscode is that it'll generate a ISDEPLOYING FILE then it'll turned into DEPLOYED FILE if it is successfully deployed. But seems like the .war file still contain the older version of the files and not the latest unlike what is happening for eclipse. When I open the DEPLOYED FILE seems like it is not a package and contain the text of the .war deployed. Notice the time frame difference between the ISDEPLOYING FILE and DEPLOYED FILE too. 

I am quite new to these, please be patient with me.

**Comment by robstryker** [comment]
It's worth noting that the linked example does not include a `bin` folder example. So that would be something like:

```
{
			"source-path": "bin/",
			"deploy-path": "/WEB-INF/classes/"
},
```

**Comment by robstryker** [comment]
The workaround listed indicates how to properly use the tool to get the desired results.
