### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by matheusalencar23** [redhat-developer/vscode-server-connector#613]
how can i set environment variables for a tomcat server using the community server connector in vscode?

**Comment by robstryker** [comment]
"mapProperty.launch.env" - allow to override or add to the environment being passed to a server upon startup. This property's value should be a object with a set of key-value pairs, where the key should be a desired environment variable, and the value being the value of that object.*

Basically, right click the server and select edit. It should show up in json format in an editor. Then you can add this field to the json. 

Here's a user example from a previous bug report where someone did this:   https://github.com/imaperson/serverdebugtest/blob/main/README.md

**Comment by matheusalencar23** [comment]
> "mapProperty.launch.env" - allow to override or add to the environment being passed to a server upon startup. This property's value should be a object with a set of key-value pairs, where the key should be a desired environment variable, and the value being the value of that object.*
> 
> Basically, right click the server and select edit. It should show up in json format in an editor. Then you can add this field to the json.
> 
> Here's a user example from a previous bug report where someone did this: https://github.com/imaperson/serverdebugtest/blob/main/README.md


worked fine here, thanks a lot
