### ISSUE TITLE
release 0.26.17 breaks on file present in multiple rsp.assembly.json mappings (0.26.16 is ok)

### ISSUE THREAD

**Issue by infocamerepp** [redhat-developer/vscode-server-connector#629]
15:31:39.234 [onPool-worker-1] ERROR o.j.t.r.s.s.p.AbstractFilesystemPublishController:289 - Error publishing module xxx to server JBoss EAP 7.3: error copying mapping xxx\target\classes\ to xxx\WEB-INF\classes\
java.nio.file.FileAlreadyExistsException: xxx.class

mappings:

{
	"mappings": [
		{
			"source-path": "target/xxx/",
			"deploy-path": "/"
		},
		{
			"source-path": "target/classes/it/",
			"deploy-path": "/WEB-INF/classes/it/"
		}
	]
}

**Comment by gbrandalise** [comment]
@robstryker 

You may need to check if the destination folder already exists before trying to create it.

I don't realized that when I added this line

**Comment by robstryker** [comment]
@infocamerepp  Please close this issue if the newest release is fixed for you. 

@gbrandalise  Please open a new issue with what issue you are attempting to solve with your PR, as well as an updated PR.  Thanks in advance.

**Comment by infocamerepp** [comment]
fixed
