### ISSUE TITLE
Create UI test suite

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-server-connector#86]

**Comment by dgolovin** [comment]
There is no UI test for VSCode yet

**Comment by odockal** [comment]
@dgolovin I am taking this as I am already working on it.

**Comment by odockal** [comment]
We have already merged https://github.com/redhat-developer/vscode-server-connector/pull/433 and https://github.com/redhat-developer/vscode-server-connector/pull/426. I will close this issue and create new one for follow up UI tests.
